version: "3"
services:
  nucomp-database:
    image: mongo:6.0.6
    container_name: nucomp-project
    restart: always 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=site
      - MONGO_INITDB_ROOT_PASSWORD=site
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db

  nucomp-api:
    build: .
    restart: always
    ports:
      - 8000:8000

