version: '3'
services:
  agregas-database:
    image: mongo
    container_name: site-project
    environment:
      - MONGO_INITDB_DATABASE=site
      - MONGO_INITDB_ROOT_USERNAME=site
      - MONGO_INITDB_ROOT_PASSWORD=site
    ports:
      - 27030:27017
    volumes:
      - ./mongo/data:/data/db

